server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
        - id: complaint-service
          uri: lb://complaint-service
          predicates:
            - Path=/api/v1/complaints/**
        - id: media-service
          uri: lb://media-service
          predicates:
            - Path=/api/v1/media/**
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/api/v1/departments/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notifications/**
        - id: analytics-service
          uri: lb://analytics-service
          predicates:
            - Path=/api/v1/analytics/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
